### ISSUE TITLE
Error running radical-synapse-emulate on branch feature/named_storage

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.synapse#11]
Hello. I get the following error when I am trying to run `radical-synapse-emulate -i <profile.json>` on the branch `feature/named_storage`. This command, however, executes on the `devel` branch properly

EDIT: A word

```
Traceback (most recent call last):
  File "/home1/03662/tg829619/bin/ve.synapse/bin/radical-synapse-emulate", line 61, in <module>
    emu_source(sys.argv[2])
  File "/home1/03662/tg829619/bin/ve.synapse/bin/radical-synapse-emulate", line 28, in emu_source
    info, ret, out = rs.emulate (src=src)
  File "/home1/03662/tg829619/bin/ve.synapse/lib/python2.7/site-packages/radical/synapse/synapse.py", line 344, in emulate
    _emulator(samples)
  File "/home1/03662/tg829619/bin/ve.synapse/lib/python2.7/site-packages/radical/synapse/synapse.py", line 268, in _emulator
    state[t].emulate(v)
  File "/home1/03662/tg829619/bin/ve.synapse/lib/python2.7/site-packages/radical/synapse/atoms/base.py", line 93, in emulate
    print "emulate  %s" % vals
```

**Comment by andre-merzky** [comment]
Could you please include the error message?  Let me try to reproduce this.  What specific profile are you running?  Thanks, Andre.
