### ISSUE TITLE
hello_synapse.py fails

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.synapse#4]
RP: fix/misc
RU: devel

examples/misc/hello_synapse.py fails with the following error:

```
|2016-01-28 21:37:02,841: radical.pilot       : MainProcess                     : Thread-3       : INFO    : [Callback]: unit unit.000009 state on pilot pilot.0000: Failed.
[Callback]: unit unit.000009 on pilot.0000: Failed.
[Callback]: #      2
stderr: [... CONTENT SHORTENED ...]
-l <samples>]
        [-ncols <columns>]
        [-o <key>] [-O <secondaryKey>]
        [-R | -r]
        [-S]
        [-s <delay>]
        [-n <nprocs>]
        [-stats <key(s)>]
        [-pid <processid>]
        [-user <username>]
        [-U <username>]
        [-u]

Traceback (most recent call last):
  File "/Users/mturilli/radical.pilot.sandbox/ve_localhost/bin/radical-synapse-sample", line 135, in <module>
    if   mode == 'sample'  : run_samples (url, cpu_flops, sto_in, sto_out, mem_rss, samples)
  File "/Users/mturilli/radical.pilot.sandbox/ve_localhost/bin/radical-synapse-sample", line 31, in run_samples
    info, ret, out = rs.emulate (samples=samples)
  File "/Users/mturilli/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/radical/synapse/synapse.py", line 328, in emulate
    info, ret, _ = profile (_emulator, samples)
  File "/Users/mturilli/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/radical/synapse/synapse.py", line 124, in profile
    load_1 = float(os.popen (_LOAD_CMD).read())
ValueError: could not convert string to float: 

2016-01-28 21:37:02,849: radical.pilot       : MainProcess                     : Thread-3       : ERROR   : unit manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/Users/mturilli/Virtualenvs/synampse/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 262, in run
    self.call_unit_state_callbacks(unit_id, new_state)
  File "/Users/mturilli/Virtualenvs/synampse/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 199, in call_unit_state_callbacks
    cb(self._shared_data[unit_id]['facade_object'], new_state)
  File "hello_synapse.py", line 106, in unit_state_cb
    sys.exit(2)
SystemExit: 2
```

As requested I did not investigated further.

**Comment by andre-merzky** [comment]
Ah bugger - my immediate guess would be that output of some commands on MacOS is different than on Linux.  Who would have thought... :P  Let me try to get this going on MacOS...

**Comment by andre-merzky** [comment]
Hey Matteo -- that specific problem is fixed in synapse devel now -- but other problems pop up on MacOS.  Specifically, the `/proc/` is not supported, and most of the system profiling stuff I am using is neither.  In the long run I can probably get those parts isolated sufficiently from the emulation part (which is way more portable) -- but in the short run, I think it would be best to limit the use to Linux...

Sorry that this makes testing more cumbersome :/  I'll open a new ticket on MacOS emulation support.

**Comment by andre-merzky** [comment]
I am closing this   ticket in favor of #5.
